sparse_encoder:
  input_dim: 128
  hidden_dim: 128
  output_dim: 128

high_level_model:
  llm_model_name: meta-llama/Llama-3.2-3B
  input_dim: 128
  hidden_dim: 128
  output_dim: 128

lane_probability:
  agent_dim: 128
  lane_dim: 128
  hidden_dim: 128
  num_lanes: 6

laplace_decoder:
  input_dim: 128
  output_dim: 2

mamba:
  hidden_dim: 128
  num_blocks: 4