task: tune

tune:
  n_trials: 20  # Number of hyperparameter optimization trials
  sampler: "random"  # Sampling method: "random", "grid", or "bayesian"
  search_space:
    lr:  # Learning rate range
      min: 1e-5
      max: 1e-2
    batch_size:  # Batch size options
      choices: [16, 32, 64]
    hidden_dim:  # Hidden layer dimensions
      min: 128
      max: 512
      step: 64