# configs/config.yaml
defaults:
  - tasks/train  # 기본 작업
  #- tasks/test   # 테스트 작업 추가
  - modules/data_loader
  - modules/model
  - modules/wandb

train:
  lr: 0.001
  epochs: 10
  weight_decay: 0.01
  batch_size: 16
  gpus: 1

test:
  batch_size: 16
  gpus: 1
  data_root: /home/user/data/Nuscenes
  checkpoint: /home/user/Traj-LLM/imjaegyun/Traj-LLM/outputs/2025-01-08/01-58-51/Traj-LLM/2yau9l6p/checkpoints/epoch=99-step=4300.ckpt
  output_file: predictions.json

modules:
  high_level_model:
    llm_model_name: meta-llama/Llama-3.2-3B
    input_dim: 128
    hidden_dim: 256
    output_dim: 128